In [1]:
try:
    import google.colab  # noqa: F401

    # specify the version of DataEval (==X.XX.X) for versions other than the latest
    %pip install -q dataeval maite-datasets
except Exception:
    pass

In [2]:
import polars as pl
from maite_datasets.image_classification import CIFAR10

from dataeval import Metadata
from dataeval.config import set_max_processes
from dataeval.quality import Outliers

set_max_processes(4)
_ = pl.Config.set_tbl_rows(-1)

In [3]:
# Load in the CIFAR10 dataset
testing_dataset = CIFAR10("./data", image_set="test", download=True)

# Create the metadata for the dataset
metadata = Metadata(testing_dataset)

In [4]:
# Initialize the Duplicates class
outliers = Outliers(outlier_threshold=("zscore", 3.5))

# Evaluate the data
results = outliers.evaluate(testing_dataset)

# Also evaluate the data classwise
results_classwise = results.classwise(metadata)

In [5]:
print(f"Total number of images with an issue: {len(results.aggregate_by_item())}")

Total number of images with an issue: 319

In [6]:
print(f"Total number of images with an issue (classwise): {len(results_classwise.aggregate_by_item())}")

Total number of images with an issue (classwise): 336

In [7]:
# View issues by metric
results.aggregate_by_metric()

shape: (11, 2)
┌─────────────┬───────┐
│ metric_name ┆ Total │
│ ---         ┆ ---   │
│ cat         ┆ u32   │
╞═════════════╪═══════╡
│ entropy     ┆ 148   │
│ zeros       ┆ 79    │
│ kurtosis    ┆ 78    │
│ skew        ┆ 50    │
│ brightness  ┆ 49    │
│ contrast    ┆ 41    │
│ var         ┆ 37    │
│ mean        ┆ 10    │
│ std         ┆ 4     │
│ darkness    ┆ 2     │
│ sharpness   ┆ 2     │
└─────────────┴───────┘

In [8]:
# View issues by metric (classwise)
results_classwise.aggregate_by_metric()

shape: (10, 2)
┌─────────────┬───────┐
│ metric_name ┆ Total │
│ ---         ┆ ---   │
│ cat         ┆ u32   │
╞═════════════╪═══════╡
│ entropy     ┆ 122   │
│ kurtosis    ┆ 115   │
│ zeros       ┆ 75    │
│ contrast    ┆ 47    │
│ var         ┆ 46    │
│ skew        ┆ 34    │
│ brightness  ┆ 33    │
│ std         ┆ 11    │
│ mean        ┆ 10    │
│ darkness    ┆ 5     │
└─────────────┴───────┘

In [9]:
# View issues by class
results.aggregate_by_class(metadata)

shape: (11, 13)
┌────────────┬────────────┬──────────┬──────────┬───┬─────┬─────┬───────┬───────┐
│ class_name ┆ brightness ┆ contrast ┆ darkness ┆ … ┆ std ┆ var ┆ zeros ┆ Total │
│ ---        ┆ ---        ┆ ---      ┆ ---      ┆   ┆ --- ┆ --- ┆ ---   ┆ ---   │
│ cat        ┆ u32        ┆ u32      ┆ u32      ┆   ┆ u32 ┆ u32 ┆ u32   ┆ u32   │
╞════════════╪════════════╪══════════╪══════════╪═══╪═════╪═════╪═══════╪═══════╡
│ airplane   ┆ 32         ┆ 2        ┆ 0        ┆ … ┆ 1   ┆ 4   ┆ 7     ┆ 189   │
│ bird       ┆ 6          ┆ 10       ┆ 0        ┆ … ┆ 1   ┆ 4   ┆ 7     ┆ 78    │
│ cat        ┆ 2          ┆ 4        ┆ 1        ┆ … ┆ 0   ┆ 5   ┆ 13    ┆ 42    │
│ automobile ┆ 0          ┆ 5        ┆ 0        ┆ … ┆ 0   ┆ 5   ┆ 11    ┆ 35    │
│ deer       ┆ 1          ┆ 7        ┆ 0        ┆ … ┆ 0   ┆ 0   ┆ 7     ┆ 35    │
│ frog       ┆ 0          ┆ 5        ┆ 0        ┆ … ┆ 0   ┆ 4   ┆ 14    ┆ 34    │
│ horse      ┆ 0          ┆ 4        ┆ 1        ┆ … ┆ 1   ┆ 6   ┆ 10    ┆ 29    │
│ ship       ┆ 5          ┆ 0        ┆ 0        ┆ … ┆ 1   ┆ 3   ┆ 1     ┆ 23    │
│ dog        ┆ 2          ┆ 2        ┆ 0        ┆ … ┆ 0   ┆ 3   ┆ 7     ┆ 18    │
│ truck      ┆ 1          ┆ 2        ┆ 0        ┆ … ┆ 0   ┆ 3   ┆ 2     ┆ 17    │
│ Total      ┆ 49         ┆ 41       ┆ 2        ┆ … ┆ 4   ┆ 37  ┆ 79    ┆ 500   │
└────────────┴────────────┴──────────┴──────────┴───┴─────┴─────┴───────┴───────┘

In [10]:
# View issues by class (classwise)
results_classwise.aggregate_by_class(metadata)

shape: (11, 12)
┌────────────┬────────────┬──────────┬──────────┬───┬─────┬─────┬───────┬───────┐
│ class_name ┆ brightness ┆ contrast ┆ darkness ┆ … ┆ std ┆ var ┆ zeros ┆ Total │
│ ---        ┆ ---        ┆ ---      ┆ ---      ┆   ┆ --- ┆ --- ┆ ---   ┆ ---   │
│ cat        ┆ u32        ┆ u32      ┆ u32      ┆   ┆ u32 ┆ u32 ┆ u32   ┆ u32   │
╞════════════╪════════════╪══════════╪══════════╪═══╪═════╪═════╪═══════╪═══════╡
│ horse      ┆ 5          ┆ 6        ┆ 1        ┆ … ┆ 1   ┆ 6   ┆ 10    ┆ 56    │
│ airplane   ┆ 0          ┆ 9        ┆ 1        ┆ … ┆ 1   ┆ 4   ┆ 8     ┆ 55    │
│ deer       ┆ 3          ┆ 7        ┆ 0        ┆ … ┆ 0   ┆ 5   ┆ 7     ┆ 54    │
│ automobile ┆ 2          ┆ 4        ┆ 0        ┆ … ┆ 0   ┆ 5   ┆ 11    ┆ 50    │
│ bird       ┆ 4          ┆ 5        ┆ 0        ┆ … ┆ 3   ┆ 6   ┆ 8     ┆ 50    │
│ ship       ┆ 5          ┆ 4        ┆ 0        ┆ … ┆ 1   ┆ 3   ┆ 3     ┆ 50    │
│ frog       ┆ 2          ┆ 4        ┆ 0        ┆ … ┆ 4   ┆ 9   ┆ 11    ┆ 49    │
│ truck      ┆ 7          ┆ 3        ┆ 2        ┆ … ┆ 0   ┆ 1   ┆ 3     ┆ 46    │
│ cat        ┆ 2          ┆ 3        ┆ 1        ┆ … ┆ 0   ┆ 4   ┆ 8     ┆ 45    │
│ dog        ┆ 3          ┆ 2        ┆ 0        ┆ … ┆ 1   ┆ 3   ┆ 6     ┆ 43    │
│ Total      ┆ 33         ┆ 47       ┆ 5        ┆ … ┆ 11  ┆ 46  ┆ 75    ┆ 498   │
└────────────┴────────────┴──────────┴──────────┴───┴─────┴─────┴───────┴───────┘

In [11]:
### TEST ASSERTION CELL ###
print(results.shape[0])
assert results.shape[0] == 500

500