In [1]:
try:
    import google.colab  # noqa: F401

    # specify the version of DataEval (==X.XX.X) for versions other than the latest
    %pip install -q dataeval maite-datasets
except Exception:
    pass

In [2]:
import polars as pl
from maite_datasets.image_classification import CIFAR10

from dataeval import Metadata
from dataeval.config import set_max_processes
from dataeval.quality import Outliers

set_max_processes(4)
_ = pl.Config.set_tbl_rows(-1)

In [3]:
# Load in the CIFAR10 dataset
testing_dataset = CIFAR10("./data", image_set="test", download=True)

# Create the metadata for the dataset
metadata = Metadata(testing_dataset)

In [4]:
# Initialize the Outliers class
outliers = Outliers()

# Evaluate the data
results = outliers.evaluate(testing_dataset)

# Also evaluate the data classwise
results_classwise = results.classwise(metadata)

In [5]:
print(f"Total number of images with an issue: {len(results.aggregate_by_item())}")

Total number of images with an issue: 319

In [6]:
print(f"Total number of images with an issue (classwise): {len(results_classwise.aggregate_by_item())}")

Total number of images with an issue (classwise): 322

In [7]:
# View issues by metric
results.aggregate_by_metric()

shape: (7, 2)
┌─────────────┬───────┐
│ metric_name ┆ Total │
│ ---         ┆ ---   │
│ cat         ┆ u32   │
╞═════════════╪═══════╡
│ zeros       ┆ 197   │
│ kurtosis    ┆ 94    │
│ entropy     ┆ 60    │
│ skew        ┆ 29    │
│ contrast    ┆ 15    │
│ brightness  ┆ 8     │
│ var         ┆ 1     │
└─────────────┴───────┘

In [8]:
# View issues by metric (classwise)
results_classwise.aggregate_by_metric()

shape: (8, 2)
┌─────────────┬───────┐
│ metric_name ┆ Total │
│ ---         ┆ ---   │
│ cat         ┆ u32   │
╞═════════════╪═══════╡
│ zeros       ┆ 199   │
│ kurtosis    ┆ 83    │
│ entropy     ┆ 61    │
│ contrast    ┆ 15    │
│ skew        ┆ 13    │
│ brightness  ┆ 5     │
│ var         ┆ 4     │
│ darkness    ┆ 3     │
└─────────────┴───────┘

In [9]:
# View issues by class
results.aggregate_by_class(metadata)

shape: (11, 9)
┌────────────┬────────────┬──────────┬─────────┬───┬──────┬─────┬───────┬───────┐
│ class_name ┆ brightness ┆ contrast ┆ entropy ┆ … ┆ skew ┆ var ┆ zeros ┆ Total │
│ ---        ┆ ---        ┆ ---      ┆ ---     ┆   ┆ ---  ┆ --- ┆ ---   ┆ ---   │
│ cat        ┆ u32        ┆ u32      ┆ u32     ┆   ┆ u32  ┆ u32 ┆ u32   ┆ u32   │
╞════════════╪════════════╪══════════╪═════════╪═══╪══════╪═════╪═══════╪═══════╡
│ airplane   ┆ 7          ┆ 1        ┆ 35      ┆ … ┆ 19   ┆ 0   ┆ 21    ┆ 127   │
│ bird       ┆ 1          ┆ 1        ┆ 6       ┆ … ┆ 4    ┆ 1   ┆ 24    ┆ 57    │
│ cat        ┆ 0          ┆ 1        ┆ 3       ┆ … ┆ 3    ┆ 0   ┆ 27    ┆ 42    │
│ frog       ┆ 0          ┆ 1        ┆ 4       ┆ … ┆ 0    ┆ 0   ┆ 31    ┆ 39    │
│ automobile ┆ 0          ┆ 1        ┆ 3       ┆ … ┆ 0    ┆ 0   ┆ 31    ┆ 36    │
│ deer       ┆ 0          ┆ 6        ┆ 1       ┆ … ┆ 2    ┆ 0   ┆ 15    ┆ 33    │
│ horse      ┆ 0          ┆ 1        ┆ 1       ┆ … ┆ 0    ┆ 0   ┆ 19    ┆ 22    │
│ ship       ┆ 0          ┆ 0        ┆ 3       ┆ … ┆ 0    ┆ 0   ┆ 10    ┆ 20    │
│ dog        ┆ 0          ┆ 1        ┆ 2       ┆ … ┆ 0    ┆ 0   ┆ 12    ┆ 15    │
│ truck      ┆ 0          ┆ 2        ┆ 2       ┆ … ┆ 1    ┆ 0   ┆ 7     ┆ 13    │
│ Total      ┆ 8          ┆ 15       ┆ 60      ┆ … ┆ 29   ┆ 1   ┆ 197   ┆ 404   │
└────────────┴────────────┴──────────┴─────────┴───┴──────┴─────┴───────┴───────┘

In [10]:
# View issues by class (classwise)
results_classwise.aggregate_by_class(metadata)

shape: (11, 10)
┌────────────┬────────────┬──────────┬──────────┬───┬──────┬─────┬───────┬───────┐
│ class_name ┆ brightness ┆ contrast ┆ darkness ┆ … ┆ skew ┆ var ┆ zeros ┆ Total │
│ ---        ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---  ┆ --- ┆ ---   ┆ ---   │
│ cat        ┆ u32        ┆ u32      ┆ u32      ┆   ┆ u32  ┆ u32 ┆ u32   ┆ u32   │
╞════════════╪════════════╪══════════╪══════════╪═══╪══════╪═════╪═══════╪═══════╡
│ airplane   ┆ 0          ┆ 2        ┆ 0        ┆ … ┆ 2    ┆ 1   ┆ 21    ┆ 46    │
│ cat        ┆ 0          ┆ 1        ┆ 0        ┆ … ┆ 3    ┆ 0   ┆ 24    ┆ 45    │
│ truck      ┆ 3          ┆ 2        ┆ 2        ┆ … ┆ 2    ┆ 0   ┆ 16    ┆ 45    │
│ frog       ┆ 0          ┆ 1        ┆ 0        ┆ … ┆ 0    ┆ 0   ┆ 31    ┆ 41    │
│ automobile ┆ 0          ┆ 0        ┆ 0        ┆ … ┆ 0    ┆ 0   ┆ 25    ┆ 39    │
│ bird       ┆ 0          ┆ 0        ┆ 0        ┆ … ┆ 2    ┆ 2   ┆ 20    ┆ 37    │
│ deer       ┆ 1          ┆ 6        ┆ 0        ┆ … ┆ 3    ┆ 0   ┆ 15    ┆ 37    │
│ horse      ┆ 0          ┆ 2        ┆ 1        ┆ … ┆ 0    ┆ 0   ┆ 19    ┆ 34    │
│ ship       ┆ 1          ┆ 0        ┆ 0        ┆ … ┆ 1    ┆ 1   ┆ 13    ┆ 33    │
│ dog        ┆ 0          ┆ 1        ┆ 0        ┆ … ┆ 0    ┆ 0   ┆ 15    ┆ 26    │
│ Total      ┆ 5          ┆ 15       ┆ 3        ┆ … ┆ 13   ┆ 4   ┆ 199   ┆ 383   │
└────────────┴────────────┴──────────┴──────────┴───┴──────┴─────┴───────┴───────┘

In [11]:
### TEST ASSERTION CELL ###
print(results.shape[0])
assert results.shape[0] == 404

404